package election;

public class GUI_Candidate_MENU extends javax.swing.JFrame {

    /**
     * Creates new form Member_MENU_GUI
     */
    Candidate c;

    public GUI_Candidate_MENU() {
        initComponents();
    }

    public GUI_Candidate_MENU(Candidate c) {
        initComponents();
        this.c = c;
        welcome.setText(c.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Backbtn1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Backbtn2 = new javax.swing.JButton();
        viewprofilebtn = new javax.swing.JButton();
        createeventbtn = new javax.swing.JButton();
        viewmsgsbtn = new javax.swing.JButton();
        viewstatsbtn = new javax.swing.JButton();
        createeventbtn1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        welcome = new javax.swing.JLabel();
        welcome1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        Backbtn1.setBackground(new java.awt.Color(69, 152, 144));
        Backbtn1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Backbtn1.setText("<<");
        Backbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Backbtn1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Election Online System");

        jPanel1.setBackground(new java.awt.Color(69, 152, 144));

        jPanel2.setBackground(new java.awt.Color(1, 33, 46));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(69, 152, 144));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/voteresized.png"))); // NOI18N
        jLabel3.setText("Election Online System");

        Backbtn2.setBackground(new java.awt.Color(69, 152, 144));
        Backbtn2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Backbtn2.setText("<<");
        Backbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Backbtn2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(Backbtn2)
                .addGap(30, 30, 30)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(Backbtn2))
                .addContainerGap())
        );

        viewprofilebtn.setBackground(new java.awt.Color(1, 33, 46));
        viewprofilebtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        viewprofilebtn.setForeground(new java.awt.Color(255, 255, 255));
        viewprofilebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/profileresized.png"))); // NOI18N
        viewprofilebtn.setText("View Profile");
        viewprofilebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewprofilebtnActionPerformed(evt);
            }
        });

        createeventbtn.setBackground(new java.awt.Color(1, 33, 46));
        createeventbtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        createeventbtn.setForeground(new java.awt.Color(255, 255, 255));
        createeventbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/upcomingresized.png"))); // NOI18N
        createeventbtn.setText("Create Event");
        createeventbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createeventbtnActionPerformed(evt);
            }
        });

        viewmsgsbtn.setBackground(new java.awt.Color(1, 33, 46));
        viewmsgsbtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        viewmsgsbtn.setForeground(new java.awt.Color(255, 255, 255));
        viewmsgsbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/checkresized.png"))); // NOI18N
        viewmsgsbtn.setText("View Messages");
        viewmsgsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewmsgsbtnActionPerformed(evt);
            }
        });

        viewstatsbtn.setBackground(new java.awt.Color(1, 33, 46));
        viewstatsbtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        viewstatsbtn.setForeground(new java.awt.Color(255, 255, 255));
        viewstatsbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bar-chartresized.png"))); // NOI18N
        viewstatsbtn.setText("View statistics ");
        viewstatsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewstatsbtnActionPerformed(evt);
            }
        });

        createeventbtn1.setBackground(new java.awt.Color(1, 33, 46));
        createeventbtn1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        createeventbtn1.setForeground(new java.awt.Color(255, 255, 255));
        createeventbtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/upcomingresized.png"))); // NOI18N
        createeventbtn1.setText("Manage Events");
        createeventbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createeventbtn1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(1, 33, 46));

        welcome.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        welcome.setForeground(new java.awt.Color(1, 33, 46));

        welcome1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        welcome1.setForeground(new java.awt.Color(1, 33, 46));
        welcome1.setText("Welcome Back");

        jButton2.setBackground(new java.awt.Color(1, 33, 46));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/resultsresized.png"))); // NOI18N
        jButton2.setText("View Resultss");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(createeventbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewstatsbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(viewmsgsbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(createeventbtn1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(welcome1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(viewprofilebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(172, 172, 172))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(welcome1)
                    .addComponent(welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(viewprofilebtn)
                            .addComponent(jButton2))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(createeventbtn)
                            .addComponent(createeventbtn1))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(viewmsgsbtn)
                            .addComponent(viewstatsbtn)))
                    .addComponent(jLabel1))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void viewprofilebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewprofilebtnActionPerformed
        GUI_View_Profile profile = new GUI_View_Profile(c);
        profile.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_viewprofilebtnActionPerformed

    private void createeventbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createeventbtnActionPerformed
        GUI_Create_Event event = new GUI_Create_Event(c);
        event.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_createeventbtnActionPerformed

    private void viewmsgsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewmsgsbtnActionPerformed
        GUI_view_message vm = new GUI_view_message(c);
        vm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_viewmsgsbtnActionPerformed

    private void viewstatsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewstatsbtnActionPerformed
        GUI_View_Statistics stat = new GUI_View_Statistics(c);
        stat.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_viewstatsbtnActionPerformed

    private void Backbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Backbtn1ActionPerformed
        GUI_LoginForm login = new GUI_LoginForm();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Backbtn1ActionPerformed

    private void Backbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Backbtn2ActionPerformed
        GUI_LoginForm login = new GUI_LoginForm();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Backbtn2ActionPerformed

    private void createeventbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createeventbtn1ActionPerformed
        GUI_Manage_Event manage = new GUI_Manage_Event(c);
        manage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_createeventbtn1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        GUI_View_Results results = new GUI_View_Results(c);
        results.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Candidate_MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Candidate_MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Candidate_MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Candidate_MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Candidate_MENU().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Backbtn1;
    private javax.swing.JButton Backbtn2;
    private javax.swing.JButton createeventbtn;
    private javax.swing.JButton createeventbtn1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton viewmsgsbtn;
    private javax.swing.JButton viewprofilebtn;
    private javax.swing.JButton viewstatsbtn;
    private javax.swing.JLabel welcome;
    private javax.swing.JLabel welcome1;
    // End of variables declaration//GEN-END:variables
}
